version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && python manage.py collecstatic"

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - celery
      - celery-beat

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A my_project worker -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A my_project beat -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
