# Generated by Django 5.0.2 on 2024-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_category_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.SmallIntegerField(default=10),
        ),
    ]
